---
abstract: 'Make an attribute searchable for an external index.'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Moose: 0
  MooseX::Storage::Deferred: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Meta-Attribute-Searchable
requires:
  Moose::Role: 0
resources:
  repository: https://github.com/gphat/moosex-meta-attribute-searchable
version: 0.01
